CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO INCREMENT,
    NOME_DEPARTAMENTO VARCHAR (50),
    LOCALIZACAO_DEPARTAMENTO VARCHAR (60)
);

CREATE TABLE COLABORADOR(
    ID_COLABORADOR INT PRIMARY KEY AUTO INCREMENT,
    NOME_COLABORADOR VARCHAR (50),
    CPF_COLABORADOR DECIMAL
)