CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO INCREMENT,
    NOME_DEPARTAMENTO VARCHAR (50),
    LOCALIZACAO_DEPARTAMENTO VARCHAR (60)
    ID_COLABORADOR INT AUTO INCREMENT,
    FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE COLABORADOR(
    ID_COLABORADOR INT PRIMARY KEY AUTO INCREMENT,
    NOME_COLABORADOR VARCHAR (50),
    CPF_COLABORADOR INT UNIQUE,
    EMAIL_CORP_COLABORADOR VARCHAR UNIQUE (80),
    CARGO_COLABORADOR VARCHAR (50),
    DATA_ADMISSAO DATE,
    ID_EQUIPAMENTO INT AUTO INCREMENT,
    FOREIGN KEY (ID_EQUIPAMENTO)
    REFERENCES EQUIPAMENTO (ID_EQUIPAMENTO)
    
);

CREATE TABLE EQUIPAMENTO(
    ID_EQUIPAMENTO INT PRIMARY KEY AUTO INCREMENT,
    PATRIMONIO_EQUIPAMENTO INT UNIQUE,
    DESCRICAO_EQUIPAMENTO VARCHAR (100),
    FABRICANTE_EQUIPAMENTO VARCHAR (80),
    MODELO_EQUIPAMENTO VARCHAR (50),
    DATA_AQUISICAO_EQUIPAMENTO DATE,
    STATUS_EQUIPAMENTO BOOLEAN
);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT PRIMARY KEY AUTO INCREMENT,
    NOME_CATEGORIA VARCHAR,
    ID_EQUIPAMENTO INT AUTO INCREMENT,
    FOREIGN KEY (ID_EQUIPAMENTO)
    REFERENCES EQUIPAMENTO (ID_EQUIPAMENTO)
);

CREATE TABLES FORNECEDOR(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR (20),
    CNPJ_FORNECEDOR INT UNIQUE,
    TELEFONE_FORNECEDOR VARCHAR UNIQUE (40),
    CIDADE_FORNECEDOR VARCHAR (30),
    ID_EQUIPAMENTO INT AUTO INCREMENT,
    FOREIGN KEY (ID_EQUIPAMENTO)
    REFERENCES EQUIPAMENTO (ID_EQUIPAMENTO)
)

CREATE TABLE CHAMADO_SUPORTE(
    ID_CHAMADO INT PRIMARY KEY AUTO INCREMENT
    DATA_ABERTURA_CHAMADO DATE,
    DESCRICAO_PROBLEMA VARCHAR (40),
    PRIORIDADE_CHAMADO VARCHAR (40),
    STATUS_CHAMADO BOOLEAN,
    DATA_ENCERRAMENTO_CHAMADO DATE
);

CREATE TABLE MANUTENCAO(
    ID_MANUTENCAO INT PRIMARY KEY AUTO INCREMENT,
    DATA_MANUTENCAO DATE,
    DESCRICAO_SERVICO VARCHAR (40),
    CUSTO_MANUTENCAO DECIMAL
);

