CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO INCREMENT,
    NOME_DEPARTAMENTO VARCHAR (50),
    LOCALIZACAO_DEPARTAMENTO VARCHAR (60)
    ID_COLABORADOR,
    FOREIGN KEY (ID_COLABORADOR)
    REFERENCES COLABORADOR (ID_COLABORADOR)
);

CREATE TABLE COLABORADOR(
    ID_COLABORADOR INT PRIMARY KEY AUTO INCREMENT,
    NOME_COLABORADOR VARCHAR (50),
    CPF_COLABORADOR INT UNIQUE,
    EMAIL_CORP_COLABORADOR VARCHAR UNIQUE (80),
    CARGO_COLABORADOR VARCHAR (50),
    DATA_ADMISSAO DATE
);

CREATE TABLE EQUIPAMENTO(
    ID_EQUIPAMENTO INT PRIMARY KEY AUTO INCREMENT,
    PATRIMONIO_EQUIPAMENTO INT UNIQUE,
    DESCRICAO_EQUIPAMENTO VARCHAR (100),
    FABRICANTE_EQUIPAMENTO VARCHAR (80),
    
)

