INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO, LOCALIZACAO_DEPARTMENTO)
VALUE
('PRODUÇÃO', 'BLOCO 1')
('ENGENHARIA', 'BLOCO 2')
('QUALIDADE', 'BLOCO 3')
('LOGÍSTICA', 'BLOCO 4')
('TECNOLOGIA DA INFORMAÇÃO', 'BLOCO 5');

INSERT INTO COLABORADOR (NOME_COLABORADOR, CPF_COLABORADOR, EMAIL_CORP_COLABORADOR, CARGO_COLABORADOR, )