SELECT ID_DEPARTAMENTO, NOME_DEPARTAMENTO -- Liste todos os departamentos cadastrados na empresa.
FROM DEPARTAMENTO;

SELECT NOME_COLABORADOR, CARGO_COLABORADOR, EMAIL_CORP_COLABORADOR -- Liste o nome, cargo e e-mail corporativo de todos os colaboradores.
FROM COLABORADOR;

SELECT PATRIMONIO_EQUIPAMENTO, DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO -- Exiba o patrimônio, descrição e fabricante de todos os equipamentos cadastrados.
FROM EQUIPAMENTO;

SELECT DESCRICAO_EQUIPAMENTO, STATUS_EQUIPAMENTO -- Exiba apenas a descrição e o status dos equipamentos.
FROM EQUIPAMENTO;

SELECT NOME_COLABORADOR, DATA_ADMISSAO
FROM COLABORADOR
WHERE DATA_ADMISSAO > ''