SELECT ID_DEPARTAMENTO, NOME_DEPARTAMENTO --Liste todos os departamentos cadastrados na empresa.
FROM DEPARTAMENTO;

SELECT NOME_COLABORADOR, CARGO_COLABORADOR, EMAIL_CORP_COLABORADOR --
FROM COLABORADOR;